### ISSUE TITLE
swipe direction

### ISSUE THREAD

**Issue by HamedGh** [loopeer/itemtouchhelper-extension#10]
Hi,
TanX for your great library,
I have 2 question:
1-How can I swipe rows from the other direction?
2-How can I swipe rows from both directions?

**Comment by ToDou** [comment]
The method same as ItemTouchHelper. See method getMovementFlags in ItemTouchHelperCallback of demo.
`return makeMovementFlags(ItemTouchHelper.UP|ItemTouchHelper.DOWN, ItemTouchHelper.START);`
