### ISSUE TITLE
Swiping the first item

### ISSUE THREAD

**Issue by taherhek** [loopeer/itemtouchhelper-extension#11]
There is an strange bug in swiping first item after swiping an other item. . 
First swipe any arbitrary item, then before clicking on the delete or refresh buttons, try to swipe the first item. It will not swipe unless you start swiping from the rightest point of item. if you try to swipe the first item by touching the middle points of it, the previous open item will respond to this swipe.

**Comment by NaikSoftware** [comment]
+1

**Comment by ToDou** [comment]
@taherhek @NaikSoftware I have fix the bug by [edf1ae8](https://github.com/loopeer/itemtouchhelper-extension/commit/edf1ae819f6faadb51de1b1db6b9f29aa68c1ae0). Try it.

**Comment by vasanihardik** [comment]
not working!
