### ISSUE TITLE
How to fix after swipe position of items then why onclick called..?

### ISSUE THREAD

**Issue by surinder97815** [loopeer/itemtouchhelper-extension#13]
I'm trying to use drag to swipe functionality in my activity with this code ,everything is work fine but one problem is there when im trying to swipe items from one position to another then after dropping the item on new position then immediately onclick function called how i can fix this...?  very urgent

**Comment by ToDou** [comment]
Have you ran the demo.Try drag items.Is there some difference between those?

2017-02-06 16:14 GMT+08:00 surinder97815 <notifications@github.com>:
