### ISSUE TITLE
How to disable swipe for particular item only.

### ISSUE THREAD

**Issue by nikunjsakhrelia** [loopeer/itemtouchhelper-extension#17]
I seen that even though i provide different view for different type it still allow to swipe. I want something where it only allow swipe on certain items.

**Comment by ToDou** [comment]
See the code https://github.com/loopeer/itemtouchhelper-extension/commit/60768c2e56e424852b9fc66fe586aab15feed2d1

**Comment by nikunjsakhrelia** [comment]
Great, thanks for the quick reply and update.
