### ISSUE TITLE
Can you add a drag to sort feature

### ISSUE THREAD

**Issue by naiyu** [loopeer/itemtouchhelper-extension#2]
Can you add a drag to sort feature

**Comment by ToDou** [comment]
Sorry to response to you too late. I have saw the drag in the itemtouchhelper. This itemtouchhelper-extension do not conflict with the drag.Just in the ItemTouchHelperCallback you should let the parent to do drag matters. Just let do **super.onChildDraw(...)** in the method **onChildDraw**.When drag item to move by that method then to call **ItemTouchUIUtil.onDraw**At last you can see the last test [commit](https://github.com/loopeer/itemtouchhelper-extension/commit/187fbda81696faabb2c85d9b02decaf42bf10db3)
