### ISSUE TITLE
Swipe in both directions

### ISSUE THREAD

**Issue by gemiren** [loopeer/itemtouchhelper-extension#4]
First of all, thanks for the nice library! The code looks it only supports to open the swipe content view at the end of the item. Does it support to open the swiping content views at both ends of the item at the same time?

**Comment by ToDou** [comment]
Do you mean swipe from the left?

**Comment by gemiren** [comment]
Yes.

**Comment by ToDou** [comment]
See the **ItemTouchHelperCallback** in the example package. You can add movementFlags ItemTouchHelper.END with the START. Just like
```java
    @Override
    public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
        return makeMovementFlags(ItemTouchHelper.UP|ItemTouchHelper.DOWN, ItemTouchHelper.START|ItemTouchHelper.END);
    }
```

**Comment by gemiren** [comment]
But there's only one method to get the swiping content size getActionWidth(). I'd expect to have two methods such as getActionWidthStart() and getActionWidthEnd() so it can be used for different swiping content size at the each ends. Thanks.

**Comment by ToDou** [comment]
Use type or add your some other condition by yourself.  May be you can by the dx.
