### ISSUE TITLE
How to disable the swiping dynamically?

### ISSUE THREAD

**Issue by gemiren** [loopeer/itemtouchhelper-extension#5]
Is there a way to enable and disable the swiping on the item dynamically? Thanks.

**Comment by ToDou** [comment]
You mean some item can swipe and some one can not?

**Comment by ToDou** [comment]
If that.You can return move flags with zero by the item viewholder viewtype.
```java
    @Override
    public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
        if (viewHolder.getItemViewType() == ITEM_TYPE_ACTION_WIDTH_NO_SPRING) return 0;
        return makeMovementFlags(ItemTouchHelper.UP|ItemTouchHelper.DOWN, ItemTouchHelper.START|ItemTouchHelper.END);
    }
```

**Comment by gemiren** [comment]
This will work. But it requires to change the view type of a view holder. What I like to do is to enable and disable the swiping on the same item and same view type. Thanks.

**Comment by ToDou** [comment]
You can downcast to your custom viewholder.Then do something.
