### ISSUE TITLE
点击事件触发有误

### ISSUE THREAD

**Issue by Bvin** [loopeer/itemtouchhelper-extension#6]
有时候打开Action然后再向右滑到原来位置，会触发click事件，而且有时候滑动会删除掉这个item，不知是不是触发到了SwipeThreshold，SwipeThreshold和ActionWidth有没有兼容好呢？

**Comment by ToDou** [comment]
有个bug这里，好想把cancel事件也弄来触发click事件了，修复了下，再试试。1.0.1
