### ISSUE TITLE
建议保留向后兼容接口，放低minSdk

### ISSUE THREAD

**Issue by Bvin** [loopeer/itemtouchhelper-extension#7]
我看了一下主要是动画那部分用了高版本API，其实可以考虑吧执行动画那部分抽出来让客户端去实现。。。这一低版本就可以用noa来往下兼容

**Comment by ToDou** [comment]
你是说恢复的动画？还是滑动的时候，滑动的动画现在在ItemTouchHelperCallback onChildDraw，可以自己去实现
